this.features = function(browser) {
  var bn = browser.globals.browser_name,
      screenshotPath = 'test/screenshot/',
      baseurl = 'https://fdd5c9b3.ngrok.io/test/';

  browser
    .url(baseurl+'animation1.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/animation1.png')
    .url(baseurl+'animation2.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/animation2.png')
    .url(baseurl+'arrowKeys.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/arrowKeys.png')
    .url(baseurl+'autoHeight.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/autoHeight.png')
    .url(baseurl+'autoplay.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/autoplay.png')
    .url(baseurl+'base.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/base.png')
    .url(baseurl+'customize.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/customize.png')
    .url(baseurl+'edgePadding-gutter.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/edgePadding-gutter.png')
    .url(baseurl+'edgePadding.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/edgePadding.png')
    .url(baseurl+'few-items.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/few-items.png')
    .url(baseurl+'fixedWidth-edgePadding-gutter.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/fixedWidth-edgePadding-gutter.png')
    .url(baseurl+'fixedWidth-edgePadding.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/fixedWidth-edgePadding.png')
    .url(baseurl+'fixedWidth-gutter.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/fixedWidth-gutter.png')
    .url(baseurl+'fixedWidth.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/fixedWidth.png')
    .url(baseurl+'frame1.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/frame1.png')
    .url(baseurl+'frame2.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/frame2.png')
    .url(baseurl+'frame3.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/frame3.png')
    // .url(baseurl+'frame4.html')
    // .waitForElementPresent('.test-done', 20000)
    // .saveScreenshot(screenshotPath+bn+'/frame4.png')
    .url(baseurl+'frame5.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/frame5.png')
    .url(baseurl+'frame6.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/frame6.png')
    .url(baseurl+'gutter.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/gutter.png')
    .url(baseurl+'lazyload.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/lazyload.png')
    .url(baseurl+'mouse-drag.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/mouse-drag.png')
    .url(baseurl+'nested.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/nested.png')
    .url(baseurl+'non-loop.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/non-loop.png')
    .url(baseurl+'rewind.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/rewind.png')
    .url(baseurl+'slide-by-page.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/slide-by-page.png')
    .url(baseurl+'vertical-edgePadding-gutter.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/vertical-edgePadding-gutter.png')
    .url(baseurl+'vertical-edgePadding.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/vertical-edgePadding.png')
    .url(baseurl+'vertical-gutter.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/vertical-gutter.png')
    .url(baseurl+'vertical.html')
    .waitForElementPresent('.test-done', 20000)
    .saveScreenshot(screenshotPath+bn+'/vertical.png')
    // .url(baseurl+'start-index.html')
    // .waitForElementPresent('.test-done', 20000)
    // .saveScreenshot(screenshotPath+bn+'/start-index.png')
    .end();
};