this.base = function(browser) {
  var bn = browser.globals.browser_name;
  var baseurl = 'https://'+browser.globals.urlcode+'.ngrok.io/test/';

  browser
    .url(baseurl+'animation1.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/animation1.png')
    .url(baseurl+'animation2.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/animation2.png')
    .url(baseurl+'arrowKeys.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/arrowKeys.png')
    .url(baseurl+'autoplay.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/autoplay.png')
    .url(baseurl+'base.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/base.png')
    .url(baseurl+'customize.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/customize.png')
    .url(baseurl+'edgePadding-gutter.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/edgePadding-gutter.png')
    .url(baseurl+'edgePadding.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/edgePadding.png')
    .url(baseurl+'few-items.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/few-items.png')
    .url(baseurl+'fixedWidth-edgePadding-gutter.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/fixedWidth-edgePadding-gutter.png')
    .url(baseurl+'fixedWidth-edgePadding.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/fixedWidth-edgePadding.png')
    .url(baseurl+'fixedWidth-gutter.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/fixedWidth-gutter.png')
    .url(baseurl+'fixedWidth.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/fixedWidth.png')
    .url(baseurl+'frame.html')
    // .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/frame.png')
    .url(baseurl+'gutter.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/gutter.png')
    .url(baseurl+'lazyload.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/lazyload.png')
    .url(baseurl+'mouse-drag.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/mouse-drag.png')
    .url(baseurl+'nested.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/nested.png')
    .url(baseurl+'non-loop.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/non-loop.png')
    .url(baseurl+'rewind.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/rewind.png')
    .url(baseurl+'slide-by-page.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/slide-by-page.png')
    .url(baseurl+'vertical-edgePadding-gutter.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/vertical-edgePadding-gutter.png')
    .url(baseurl+'vertical-edgePadding.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/vertical-edgePadding.png')
    .url(baseurl+'vertical-gutter.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/vertical-gutter.png')
    .url(baseurl+'vertical.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/vertical.png')
    .url(baseurl+'autoHeight.html')
    .waitForElementPresent('.tests-done', 20000)
    .saveScreenshot('test/screenshot/'+bn+'/autoHeight.png')
    // .url(baseurl+'start-index.html')
    // .waitForElementPresent('.tests-done', 20000)
    // .saveScreenshot('test/screenshot/'+bn+'/start-index.png')
    .end();
};