// import "./ie8/isArray.js";
import "./ie8/forEach.js";
import "./ie8/map.js";
// import "./ie8/filter.js";
import "./ie8/indexOf.js";
import "./ie8/addEventListener.js";
// import "./ie8/firstElementChild.js";
// import "./ie8/lastElementChild.js";
// import "./ie8/previousElementSibling.js";
// import "./ie8/nextElementSibling.js";
import "./ie8/getComputedStyle.js";